blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.PostListView.as_view(), name="index"),
    path('posts/', views.PostAllListView.as_view(), name="post-list"),
    path('post/<int:pk>/', views.PostView.as_view(), name="post")
]

pages/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = "pages"
urlpatterns = [
    path("<slug:page_pattern>/",
         views.PageView.as_view(), name="page-detail")
]

schmerdpress/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('sp-admin/', admin.site.urls),
    path('pages/', include("pages.urls")),
    path('', include("blog.urls")),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

import datetime

# Create your models here.


class Post(models.Model):
    post_author = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField("Date of publication")

    post_title = models.CharField(max_length=2000)
    post_subtitle = models.CharField(max_length=2000, default="Post subtitle")
    post_body = models.TextField(default="Post title")

    post_image = models.CharField(
        max_length=2000)

    def __str__(self):
        return f"'{self.post_title}' - {self.post_author.username.title()}"

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

pages/models.py
from django.db import models

# Create your models here.


class Page(models.Model):
    page_pattern = models.CharField(max_length=200)

    page_title = models.CharField(max_length=200)
    page_subtitle = models.CharField(max_length=2000)

    page_image = models.CharField(max_length=2000)
    page_content = models.TextField()

    def __str__(self):
        return "{} | {}".format(self.page_title, self.page_pattern)

blog/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views import generic
from django.shortcuts import render

from .models import Post

# Create your views here.


class PostView(generic.DetailView):
    model = Post
    template_name = "blog/post.html"


class PostListView(generic.ListView):
    template_name = "blog/index.html"
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.order_by("-pub_date")[:5]


class PostAllListView(generic.ListView):
    template_name = "blog/post_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.order_by("-pub_date")

pages/views.py
from django.shortcuts import render
from django.views import generic
from .models import Page

# Create your views here.


class PageView(generic.DetailView):
    model = Page
    template_name = "pages/page_view.html"
    slug_field = "page_pattern"
    slug_url_kwarg = "page_pattern"

blog/templates/blog/header.html
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="The world's best blogging application.">
        <meta name="author" content="Olly Britton">

        <title>Schmerdpress</title>

        {% load static %}

        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">

        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

        <link href="{% static 'blog/css/clean-blog.css' %}" rel="stylesheet">

    </head>
    
    <body>

        {% include "includes/navbar.html" %}

        {% block content %}
        {% endblock content %}

        {% include "includes/footer.html" %}

        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/clean-blog.js' %}"></script>
    

    </body>

</html>

blog/templates/blog/index.html
{% extends 'blog/header.html' %}

{% block content %}

{% load static %}
<header class="masthead" style="background-image: url('{% static 'blog/img/home-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Schmerdpress</h1>
                    <span class="subheading">The world's worst fake blog.</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for post in posts %}
                <div class="post-preview">
                    <a href="{% url 'blog:post' post.pk %}">
                        <h2 class="post-title">
                            {{post.post_title}}
                        </h2>

                        {% if post.post_subtitle %}
                            <h3 class="post-subtitle">
                                {{post.post_subtitle}}
                            </h3>
                        {% endif %}

                    </a>
                    <p class="post-meta">
                    Posted by <a href="#">{{post.post_author.username}}</a> on {{post.pub_date|date:"F d, Y"}}
                    </p>
                </div>
                <hr>
            {% endfor %}
            
            <div class="clearfix">
                <a class="btn btn-primary float-right" href="{% url 'blog:post-list' %}">Older Posts &rarr;</a>
            </div>
        </div>
    </div>
</div>

<hr>

{% endblock content %}

blog/templates/blog/post.html
{% extends 'blog/header.html' %}

{% block content %}

{% if post.post_image %}
<header class="masthead" style="background-image: url('{{post.post_image}}')">
{% else %}
<header class="masthead" style="background-color: black">
{% endif %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-heading">
                    <h1>{{post.post_title}}</h1>
                    {% if post.post_subtitle %}
                    <h3 class="post-subtitle">
                        {{post.post_subtitle}}
                    </h3>
                    {% endif %}
                    <span class="meta">
                        Posted by <a href="#">{{post.post_author.username}}</a> on {{post.pub_date|date:"F d, Y"}}
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>

<article>

    <div class="container">

        <div class="row">

            <div class="col-lg-8 col-md-10 mx-auto">

                {{post.post_body|safe|linebreaks}}

            </div>

        </div>

    </div>

</article>

{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'blog/header.html' %}

{% block content %}

{% load static %}
<header class="masthead" style="background-image: url('https://images.unsplash.com/photo-1501139083538-0139583c060f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-heading">
                    <h1>All Posts</h1>
                
                    <h3 class="post-subtitle">
                        Taking a waltz down memory lane.
                    </h3>
                    
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for post in posts %}
                <div class="post-preview">
                    <a href="{% url 'blog:post' post.pk %}">
                        <h2 class="post-title">
                            {{post.post_title}}
                        </h2>

                        {% if post.post_subtitle %}
                            <h3 class="post-subtitle">
                                {{post.post_subtitle}}
                            </h3>
                        {% endif %}

                    </a>
                    <p class="post-meta">
                    Posted by <a href="#">{{post.post_author.username}}</a> on {{post.pub_date|date:"F d, Y"}}
                    </p>
                </div>
                <hr>
            {% endfor %}
            
        </div>
    </div>
</div>

<hr>

{% endblock content %}

blog/templates/includes/footer.html
<footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p class="copyright text-muted">Copyright &copy; Schmerdpress 2018 to Infinity</p>
          </div>
        </div>
      </div>
    </footer>

blog/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'blog:index' %}">Schmerdpress</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:page-detail' 'about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:page-detail' 'contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a style="opactiy:50%" class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

pages/templates/pages/page_view.html
{% extends 'blog/header.html' %}

{% block content %}

{% if page.page_image %}
<header class="masthead" style="background-image: url('{{page.page_image}}')">
{% else %}
<header class="masthead" style="background-color: black">
{% endif %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-heading">
                    <h1>{{page.page_title}}</h1>
                    {% if page.page_subtitle %}
                    <h3 class="post-subtitle">
                        {{page.page_subtitle}}
                    </h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</header>

<article>

    <div class="container">

        <div class="row">

            <div class="col-lg-8 col-md-10 mx-auto">

                {{page.page_content|safe|linebreaks}}

            </div>

        </div>

    </div>

</article>

{% endblock content %}